# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-01-05 07:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('sensor_id', models.AutoField(primary_key=True, serialize=False)),
                ('sensor_id_name', models.CharField(max_length=40)),
                ('sen_note', models.CharField(max_length=200)),
                ('sen_active', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Sensor_Session',
            fields=[
                ('sen_ses_id', models.AutoField(primary_key=True, serialize=False)),
                ('sen_ses_name', models.CharField(max_length=40)),
                ('lat', models.DecimalField(decimal_places=6, max_digits=9)),
                ('lon', models.DecimalField(decimal_places=6, max_digits=9)),
                ('on_time', models.DateTimeField(verbose_name='switch on time')),
                ('last_updated', models.DateTimeField(verbose_name='last time')),
                ('ip_add', models.CharField(max_length=12)),
                ('ses_note', models.CharField(max_length=200)),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sensor.Sensor')),
            ],
        ),
        migrations.CreateModel(
            name='Session_Data',
            fields=[
                ('ses_data_id', models.AutoField(primary_key=True, serialize=False)),
                ('ses_data_name', models.CharField(max_length=40)),
                ('sound', models.FloatField(default=0)),
                ('co2', models.FloatField(default=0)),
                ('smoke', models.FloatField(default=0)),
                ('light', models.FloatField(default=0)),
                ('temp', models.FloatField(default=0)),
                ('humidity', models.FloatField(default=0)),
                ('time_rec', models.DateTimeField(auto_now_add=True)),
                ('session_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sensor.Sensor_Session')),
            ],
        ),
    ]
